///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeModelDataTabList {
/*
{
  "name": "精选",
  "code": "1"
}
*/

  String? name;
  String? code;

  HomeModelDataTabList({
    this.name,
    this.code,
  });
  HomeModelDataTabList.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['code'] = code;
    return data;
  }
}

class HomeModelDataNineMenuList {
/*
{
  "menuIcon": "https://ik.imagekit.io/guoguodad/mall/home/supermarket.png?updatedAt=1691716657143",
  "menuName": "超市",
  "menuCode": "m01",
  "h5url": "https://prodev.m.jd.com/mall/active/3xhqjGH1wMz5FaMgrfYhR22sFvqz/index.html"
}
*/

  String? menuIcon;
  String? menuName;
  String? menuCode;
  String? h5url;

  HomeModelDataNineMenuList({
    this.menuIcon,
    this.menuName,
    this.menuCode,
    this.h5url,
  });
  HomeModelDataNineMenuList.fromJson(Map<String, dynamic> json) {
    menuIcon = json['menuIcon']?.toString();
    menuName = json['menuName']?.toString();
    menuCode = json['menuCode']?.toString();
    h5url = json['h5url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['menuIcon'] = menuIcon;
    data['menuName'] = menuName;
    data['menuCode'] = menuCode;
    data['h5url'] = h5url;
    return data;
  }
}

class HomeModelDataBannerList {
/*
{
  "imgUrl": "https://ik.imagekit.io/guoguodad/mall/home/home_banner1.jpg?updatedAt=1691716405974",
  "type": "1"
}
*/

  String? imgUrl;
  String? type;

  HomeModelDataBannerList({
    this.imgUrl,
    this.type,
  });
  HomeModelDataBannerList.fromJson(Map<String, dynamic> json) {
    imgUrl = json['imgUrl']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['imgUrl'] = imgUrl;
    data['type'] = type;
    return data;
  }
}

class HomeModelDataSearchList {
/*
{
  "title": "HUAWEI Mate 60 Pro 抢先预购"
}
*/

  String? title;

  HomeModelDataSearchList({
    this.title,
  });
  HomeModelDataSearchList.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    return data;
  }
}

class HomeModelDataGoodsTbsList {
/*
{
  "title": "精选",
  "name": "为你推荐",
  "type": "1"
}
*/

  String? title;
  String? name;
  String? type;

  HomeModelDataGoodsTbsList({
    this.title,
    this.name,
    this.type,
  });
  HomeModelDataGoodsTbsList.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class HomeModelEntityDataWidgetsListList {
/*
{
  "imgUrl": "https://ik.imagekit.io/guoguodad/mall/common/goods4.jpeg?updatedAt=1691718085548",
  "description": "ASICS 亚瑟士 男鞋运动鞋 GEL-VENTURE 7 MX 抓地缓冲越野跑鞋 黑色",
  "price": "590.00",
  "type": "1"
}
*/

  String? imgUrl;
  String? description;
  String? price;
  String? type;

  HomeModelEntityDataWidgetsListList({
    this.imgUrl,
    this.description,
    this.price,
    this.type,
  });
  HomeModelEntityDataWidgetsListList.fromJson(Map<String, dynamic> json) {
    imgUrl = json['imgUrl']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['imgUrl'] = imgUrl;
    data['description'] = description;
    data['price'] = price;
    data['type'] = type;
    return data;
  }
}


class HomeModelDataWidgetsList {
/*
{
  "type": "单排",
  "title": "限时秒杀",
  "name": "查看全部",
  "list": [
    {
      "imgUrl": "https://ik.imagekit.io/guoguodad/mall/common/goods4.jpeg?updatedAt=1691718085548",
      "description": "ASICS 亚瑟士 男鞋运动鞋 GEL-VENTURE 7 MX 抓地缓冲越野跑鞋 黑色",
      "price": "590.00",
      "type": "1"
    }
  ]
}
*/

  String? type;
  String? title;
  String? name;
  List<HomeModelEntityDataWidgetsListList>? list;


  HomeModelDataWidgetsList({
    this.type,
    this.title,
    this.name,
    this.list,
  });
  HomeModelDataWidgetsList.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
    if (json['list'] != null) {
      final v = (json['list'] as List<dynamic>?)?.map((e) => HomeModelEntityDataWidgetsListList.fromJson(e as Map<String, dynamic>)).toList();
      list = v;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['title'] = title;
    data['name'] = name;
    if (list != null) {
      final v = list;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['list'] = arr0;
    }
    return data;
  }
}
class HomeModelData {
/*
{
  "goodsTbsList": [
    {
      "title": "精选",
      "name": "为你推荐",
      "type": "1"
    }
  ],
  "searchList": [
    {
      "title": "HUAWEI Mate 60 Pro 抢先预购"
    }
  ],
  "bannerList": [
    {
      "imgUrl": "https://ik.imagekit.io/guoguodad/mall/home/home_banner1.jpg?updatedAt=1691716405974",
      "type": "1"
    }
  ],
  "adUrl": "https://ik.imagekit.io/guoguodad/mall/home/ad_img.png?updatedAt=1691716521394",
  "nineMenuList": [
    {
      "menuIcon": "https://ik.imagekit.io/guoguodad/mall/home/supermarket.png?updatedAt=1691716657143",
      "menuName": "超市",
      "menuCode": "m01",
      "h5url": "https://prodev.m.jd.com/mall/active/3xhqjGH1wMz5FaMgrfYhR22sFvqz/index.html"
    }
  ],
  "tabList": [
    {
      "name": "精选",
      "code": "1"
    }
  ]
}
*/
  List<HomeModelDataWidgetsList>? widgetsList;
  List<HomeModelDataGoodsTbsList>? goodsTbsList;
  List<HomeModelDataSearchList>? searchList;
  List<HomeModelDataBannerList>? bannerList;
  String? adUrl;
  List<HomeModelDataNineMenuList>? nineMenuList;
  List<HomeModelDataTabList>? tabList;

  HomeModelData({
    this.widgetsList,
    this.goodsTbsList,
    this.searchList,
    this.bannerList,
    this.adUrl,
    this.nineMenuList,
    this.tabList,
  });
  HomeModelData.fromJson(Map<String, dynamic> json) {
    if(json['widgetsList']!=null){
      final v = (json['widgetsList'] as List<dynamic>?)?.map((e) => HomeModelDataWidgetsList.fromJson(e as Map<String, dynamic>)).toList();
      widgetsList = v;
    }
    if (json['goodsTbsList'] != null) {
      final v = (json['goodsTbsList'] as List<dynamic>?)?.map((e) => HomeModelDataGoodsTbsList.fromJson(e as Map<String, dynamic>)).toList();
      goodsTbsList = v;
    }
    if (json['searchList'] != null) {
      final v = (json['searchList'] as List<dynamic>?)?.map((e) => HomeModelDataSearchList.fromJson(e as Map<String, dynamic>)).toList();

      searchList = v;
    }
    if (json['bannerList'] != null) {
      final v = (json['bannerList'] as List<dynamic>?)?.map((e) => HomeModelDataBannerList.fromJson(e as Map<String, dynamic>)).toList();
      bannerList = v;
    }
    adUrl = json['adUrl']?.toString();
    if (json['nineMenuList'] != null) {
      final v = (json['nineMenuList'] as List<dynamic>?)?.map((e) => HomeModelDataNineMenuList.fromJson(e as Map<String, dynamic>)).toList();
      nineMenuList = v;
    }
    if (json['tabList'] != null) {
      final v = (json['tabList'] as List<dynamic>?)?.map((e) => HomeModelDataTabList.fromJson(e as Map<String, dynamic>)).toList();
      tabList = v;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (widgetsList != null) {
      final v = widgetsList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['widgetsList'] = arr0;
    }
    if (goodsTbsList != null) {
      final v = goodsTbsList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['goodsTbsList'] = arr0;
    }
    if (searchList != null) {
      final v = searchList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['searchList'] = arr0;
    }
    if (bannerList != null) {
      final v = bannerList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['bannerList'] = arr0;
    }
    data['adUrl'] = adUrl;
    if (nineMenuList != null) {
      final v = nineMenuList;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['nineMenuList'] = arr0;
    }
    if (tabList != null) {
      final v = tabList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['tabList'] = arr0;
    }
    return data;
  }
}

class HomeModel {
/*
{
  "code": "0",
  "msg": null,
  "data": {
    "goodsTbsList": [
      {
        "title": "精选",
        "name": "为你推荐",
        "type": "1"
      }
    ],
    "searchList": [
      {
        "title": "HUAWEI Mate 60 Pro 抢先预购"
      }
    ],
    "bannerList": [
      {
        "imgUrl": "https://ik.imagekit.io/guoguodad/mall/home/home_banner1.jpg?updatedAt=1691716405974",
        "type": "1"
      }
    ],
    "adUrl": "https://ik.imagekit.io/guoguodad/mall/home/ad_img.png?updatedAt=1691716521394",
    "nineMenuList": [
      {
        "menuIcon": "https://ik.imagekit.io/guoguodad/mall/home/supermarket.png?updatedAt=1691716657143",
        "menuName": "超市",
        "menuCode": "m01",
        "h5url": "https://prodev.m.jd.com/mall/active/3xhqjGH1wMz5FaMgrfYhR22sFvqz/index.html"
      }
    ],
    "tabList": [
      {
        "name": "精选",
        "code": "1"
      }
    ]
  }
}
*/

  String? code;
  String? msg;
  HomeModelData? data;

  HomeModel({
    this.code,
    this.msg,
    this.data,
  });
  HomeModel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    msg = json['msg']?.toString();
    data = (json['data'] != null) ? HomeModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['msg'] = msg;
    data['data'] = this.data!.toJson();
    return data;
  }
}
